# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/nashc-ims/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/realme/nashc-ims


PRODUCT_PACKAGES += \
    ImsService \
    mediatek-common \
    mediatek-framework \
    mediatek-gwsd \
    mediatek-gwsdv2 \
    mediatek-ims-base \
    mediatek-ims-common \
    mediatek-ims-extension-plugin \
    mediatek-ims-legacy \
    mediatek-telecom-common \
    mediatek-telephony-base \
    mediatek-telephony-common \
    mediatek-wfo-legacy
